ci: try latest cargo with nightly toolchain + for risc/s390x+freebsds:

diff --git a/.github/workflows/ffi.yml b/.github/workflows/ffi.yml
--- a/.github/workflows/ffi.yml
+++ b/.github/workflows/ffi.yml
@@ -492,92 +492,92 @@ jobs:
   #         tag: ${{ github.ref }}
   
   # build_windows:
-    runs-on: ${{ matrix.operating-system }}
-    needs: setup_matrix
-    strategy:
-      fail-fast: false
-      matrix:
-        operating-system: [windows-latest]
-        rust: [stable]
-        target:
-          - i686-pc-windows-gnu # ✅ with cross, native with cargo error: linker `i686-w64-mingw32-gcc` not found
-          - i586-pc-windows-msvc
-          - aarch64-pc-windows-gnullvm
-          - aarch64-uwp-windows-msvc
-          - i686-uwp-windows-gnu
-          - i686-uwp-windows-msvc
-          - thumbv7a-pc-windows-msvc
-          - thumbv7a-uwp-windows-msvc
-          - x86_64-pc-windows-gnullvm
-          - x86_64-uwp-windows-gnu
-          - x86_64-uwp-windows-msvc
-        crate: ${{ fromJson(needs.setup_matrix.outputs.crate) }}
-    steps:
-      - uses: actions/checkout@v3
-      - run: rustc --version || true
-        shell: bash
-      - uses: dtolnay/rust-toolchain@nightly
-        with:
-          toolchain: nightly
-          targets: ${{ matrix.target }}
-      - name: Ring 0.16.20 patch for ARM64
-        if: matrix.target == 'aarch64-pc-windows-msvc' || matrix.target == 'aarch64-pc-windows-gnullvm' || matrix.target == 'aarch64-uwp-windows-msvc'
-        run: |
-          echo ring = { git = \"https://github.com/awakecoding/ring\", branch = \"0.16.20_alpha\" } >> cargo.toml
-          cargo update
-        working-directory: rust
-        shell: bash
-      - name: install compiler deps (mingw64)
-        if: matrix.target == 'i686-pc-windows-gnu'
-        run: choco install --yes mingw
-        shell: bash
-      - name: Build ${{ matrix.crate }}
-        run: cargo build --target ${{ matrix.target }} --release
-        working-directory: rust/${{ matrix.crate }}
-        shell: bash
-      - name: Show ${{ matrix.crate }} release
-        run: ls && mkdir -p ../../artifacts/
-        working-directory: rust/target/${{ matrix.target }}/release
-        shell: bash
-      - name: Process the artifacts
-        if: matrix.crate == 'pact_ffi' && matrix.target != 'x86_64-pc-windows-gnu'
-        run: |
-          gzip -c target/${{ matrix.target }}/release/pact_ffi.dll > target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz
-          openssl dgst -sha256 -r target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz > target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz.sha256
-          gzip -c target/${{ matrix.target }}/release/pact_ffi.dll.lib > target/artifacts/pact_ffi-${{ matrix.target }}.dll.lib.gz
-          openssl dgst -sha256 -r target/artifacts/pact_ffi-${{ matrix.target }}.dll.lib.gz > target/artifacts/pact_ffi-${{ matrix.target }}.dll.lib.gz.sha256
-          gzip -c target/${{ matrix.target }}/release/pact_ffi.lib > target/artifacts/pact_ffi-${{ matrix.target }}.lib.gz
-          openssl dgst -sha256 -r target/artifacts/pact_ffi-${{ matrix.target }}.lib.gz > target/artifacts/pact_ffi-${{ matrix.target }}.lib.gz.sha256
-        working-directory: rust
-      - name: Process the artifacts
-        if: matrix.crate == 'pact_ffi' && matrix.target == 'x86_64-pc-windows-gnu'
-        run: |
-          gzip -c target/${{ matrix.target }}/release/pact_ffi.dll > target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz
-          openssl dgst -sha256 -r target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz > target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz.sha256
-        working-directory: rust
-      - name: Process the artifacts
-        if: matrix.crate == 'pact_verifier_cli'
-        run: |
-          gzip -c target/${{ matrix.target }}/release/pact_verifier_cli.exe > target/artifacts/pact_verifier_cli-${{ matrix.target }}.exe.gz
-          openssl dgst -sha256 -r target/artifacts/pact_verifier_cli-${{ matrix.target }}.exe.gz > target/artifacts/pact_verifier_cli-${{ matrix.target }}.exe.gz.sha256
-        working-directory: rust
-      - name: Process the artifacts
-        if: matrix.crate == 'pact_mock_server_cli'
-        run: |
-          gzip -c target/${{ matrix.target }}/release/pact_mock_server_cli.exe > target/artifacts/pact_mock_server_cli-${{ matrix.target }}.exe.gz
-          openssl dgst -sha256 -r target/artifacts/pact_mock_server_cli-${{ matrix.target }}.exe.gz > target/artifacts/pact_mock_server_cli-${{ matrix.target }}.exe.gz.sha256
-        working-directory: rust
-      - name: Upload the artifacts
-        if: startsWith(github.ref, 'refs/tags/libpact_ffi')  || startsWith(github.ref, 'refs/tags/pact_verifier_cli') || startsWith(github.ref, 'refs/tags/pact_mock_server_cli')
-        uses: actions/upload-artifact@v3.1.2
-        with:
-          name: release-artifacts
-          path: rust/target/artifacts
-      - name: Upload Release Assets
-        if: startsWith(github.ref, 'refs/tags/libpact_ffi')  || startsWith(github.ref, 'refs/tags/pact_verifier_cli') || startsWith(github.ref, 'refs/tags/pact_mock_server_cli')
-        uses: svenstaro/upload-release-action@2.5.0
-        with:
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          file: rust/target/artifacts/*
-          file_glob: true
-          tag: ${{ github.ref }}
+    # runs-on: ${{ matrix.operating-system }}
+    # needs: setup_matrix
+    # strategy:
+    #   fail-fast: false
+    #   matrix:
+    #     operating-system: [windows-latest]
+    #     rust: [stable]
+    #     target:
+    #       - i686-pc-windows-gnu # ✅ with cross, native with cargo error: linker `i686-w64-mingw32-gcc` not found
+    #       - i586-pc-windows-msvc
+    #       - aarch64-pc-windows-gnullvm
+    #       - aarch64-uwp-windows-msvc
+    #       - i686-uwp-windows-gnu
+    #       - i686-uwp-windows-msvc
+    #       - thumbv7a-pc-windows-msvc
+    #       - thumbv7a-uwp-windows-msvc
+    #       - x86_64-pc-windows-gnullvm
+    #       - x86_64-uwp-windows-gnu
+    #       - x86_64-uwp-windows-msvc
+    #     crate: ${{ fromJson(needs.setup_matrix.outputs.crate) }}
+    # steps:
+    #   - uses: actions/checkout@v3
+    #   - run: rustc --version || true
+    #     shell: bash
+    #   - uses: dtolnay/rust-toolchain@nightly
+    #     with:
+    #       toolchain: nightly
+    #       targets: ${{ matrix.target }}
+    #   - name: Ring 0.16.20 patch for ARM64
+    #     if: matrix.target == 'aarch64-pc-windows-msvc' || matrix.target == 'aarch64-pc-windows-gnullvm' || matrix.target == 'aarch64-uwp-windows-msvc'
+    #     run: |
+    #       echo ring = { git = \"https://github.com/awakecoding/ring\", branch = \"0.16.20_alpha\" } >> cargo.toml
+    #       cargo update
+    #     working-directory: rust
+    #     shell: bash
+    #   - name: install compiler deps (mingw64)
+    #     if: matrix.target == 'i686-pc-windows-gnu'
+    #     run: choco install --yes mingw
+    #     shell: bash
+    #   - name: Build ${{ matrix.crate }}
+    #     run: cargo build --target ${{ matrix.target }} --release
+    #     working-directory: rust/${{ matrix.crate }}
+    #     shell: bash
+    #   - name: Show ${{ matrix.crate }} release
+    #     run: ls && mkdir -p ../../artifacts/
+    #     working-directory: rust/target/${{ matrix.target }}/release
+    #     shell: bash
+    #   - name: Process the artifacts
+    #     if: matrix.crate == 'pact_ffi' && matrix.target != 'x86_64-pc-windows-gnu'
+    #     run: |
+    #       gzip -c target/${{ matrix.target }}/release/pact_ffi.dll > target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz
+    #       openssl dgst -sha256 -r target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz > target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz.sha256
+    #       gzip -c target/${{ matrix.target }}/release/pact_ffi.dll.lib > target/artifacts/pact_ffi-${{ matrix.target }}.dll.lib.gz
+    #       openssl dgst -sha256 -r target/artifacts/pact_ffi-${{ matrix.target }}.dll.lib.gz > target/artifacts/pact_ffi-${{ matrix.target }}.dll.lib.gz.sha256
+    #       gzip -c target/${{ matrix.target }}/release/pact_ffi.lib > target/artifacts/pact_ffi-${{ matrix.target }}.lib.gz
+    #       openssl dgst -sha256 -r target/artifacts/pact_ffi-${{ matrix.target }}.lib.gz > target/artifacts/pact_ffi-${{ matrix.target }}.lib.gz.sha256
+    #     working-directory: rust
+    #   - name: Process the artifacts
+    #     if: matrix.crate == 'pact_ffi' && matrix.target == 'x86_64-pc-windows-gnu'
+    #     run: |
+    #       gzip -c target/${{ matrix.target }}/release/pact_ffi.dll > target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz
+    #       openssl dgst -sha256 -r target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz > target/artifacts/pact_ffi-${{ matrix.target }}.dll.gz.sha256
+    #     working-directory: rust
+    #   - name: Process the artifacts
+    #     if: matrix.crate == 'pact_verifier_cli'
+    #     run: |
+    #       gzip -c target/${{ matrix.target }}/release/pact_verifier_cli.exe > target/artifacts/pact_verifier_cli-${{ matrix.target }}.exe.gz
+    #       openssl dgst -sha256 -r target/artifacts/pact_verifier_cli-${{ matrix.target }}.exe.gz > target/artifacts/pact_verifier_cli-${{ matrix.target }}.exe.gz.sha256
+    #     working-directory: rust
+    #   - name: Process the artifacts
+    #     if: matrix.crate == 'pact_mock_server_cli'
+    #     run: |
+    #       gzip -c target/${{ matrix.target }}/release/pact_mock_server_cli.exe > target/artifacts/pact_mock_server_cli-${{ matrix.target }}.exe.gz
+    #       openssl dgst -sha256 -r target/artifacts/pact_mock_server_cli-${{ matrix.target }}.exe.gz > target/artifacts/pact_mock_server_cli-${{ matrix.target }}.exe.gz.sha256
+    #     working-directory: rust
+    #   - name: Upload the artifacts
+    #     if: startsWith(github.ref, 'refs/tags/libpact_ffi')  || startsWith(github.ref, 'refs/tags/pact_verifier_cli') || startsWith(github.ref, 'refs/tags/pact_mock_server_cli')
+    #     uses: actions/upload-artifact@v3.1.2
+    #     with:
+    #       name: release-artifacts
+    #       path: rust/target/artifacts
+    #   - name: Upload Release Assets
+    #     if: startsWith(github.ref, 'refs/tags/libpact_ffi')  || startsWith(github.ref, 'refs/tags/pact_verifier_cli') || startsWith(github.ref, 'refs/tags/pact_mock_server_cli')
+    #     uses: svenstaro/upload-release-action@2.5.0
+    #     with:
+    #       repo_token: ${{ secrets.GITHUB_TOKEN }}
+    #       file: rust/target/artifacts/*
+    #       file_glob: true
+    #       tag: ${{ github.ref }}
