ci: test i686-pc-windows-gnu

diff --git a/.github/workflows/x-plat.yml b/.github/workflows/x-plat.yml
--- a/.github/workflows/x-plat.yml
+++ b/.github/workflows/x-plat.yml
@@ -4,8 +4,6 @@ on:
   push:
   release:
     types: [published]
-    
-# jobs:
 
 jobs:
   cross:
@@ -19,21 +17,40 @@ jobs:
         os: [ubuntu-latest]
         crate: [pact_ffi]
         target: # https://github.com/cross-rs/cross/blob/main/targets.toml
-          - x86_64-unknown-linux-gnu
-          - x86_64-unknown-linux-musl
-          - aarch64-unknown-linux-gnu
-          - aarch64-unknown-linux-musl
-          - arm-unknown-linux-gnueabi
-          - arm-unknown-linux-gnueabihf
-          - arm-unknown-linux-musleabi
-          - arm-unknown-linux-musleabihf
-          - armv7-unknown-linux-gnueabi
-          - armv7-unknown-linux-gnueabihf
-          - armv7-unknown-linux-musleabi
-          - armv7-unknown-linux-musleabihf
-          - i586-unknown-linux-gnu
-          - i686-unknown-linux-gnu
+       # ✅ These all build with cross 
+          # - x86_64-unknown-linux-gnu
+          # - x86_64-unknown-linux-musl
+          # - aarch64-unknown-linux-gnu
+          # - aarch64-unknown-linux-musl
+          # - arm-unknown-linux-gnueabi
+          # - arm-unknown-linux-gnueabihf
+          # - arm-unknown-linux-musleabi
+          # - arm-unknown-linux-musleabihf
+          # - armv7-unknown-linux-gnueabi
+          # - armv7-unknown-linux-gnueabihf
+          # - armv7-unknown-linux-musleabi
+          # - armv7-unknown-linux-musleabihf
+          # - i586-unknown-linux-gnu
+          # - i686-unknown-linux-gnu
+          # - x86_64-unknown-netbsd
+          # - x86_64-unknown-freebsd
+          # - armv5te-unknown-linux-gnueabi
+          # - armv5te-unknown-linux-musleabi
+          # - arm-linux-androideabi
+          # - armv7-linux-androideabi
+          # - aarch64-linux-android
+          # - i686-linux-android
+          # - x86_64-linux-android
+          # - thumbv7neon-linux-androideabi
+          # - thumbv7neon-unknown-linux-gnueabihf
+        # ✅ The above build with cross 
 
+          # 🚧 This did build with cross?! 
+
+          - i686-pc-windows-gnu
+          ❌
+
+          # ❌ These dont build with cross, or fall back to host and fail 
 
 
           # - i586-unknown-linux-musl
@@ -53,8 +70,6 @@ jobs:
           # = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
           # = note: use the `-l` flag to specify native libraries to link
           # = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
-          - x86_64-unknown-netbsd
-          - x86_64-unknown-freebsd
           # - i686-unknown-freebsd # fails to build
           # /usr/local/lib/gcc/i686-unknown-freebsd12/6.4.0/../../../../i686-unknown-freebsd12/bin/ld: /target/i686-unknown-freebsd/release/deps/libring-045c2b14a100e932.rlib(aes_nohw.o): in function `GFp_aes_nohw_ctr32_encrypt_blocks':
           #   /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/crypto/fipsmodule/aes/aes_nohw.c:961: undefined reference to `__stack_chk_fail_local'
@@ -77,10 +92,7 @@ jobs:
           # error: component 'rust-std' for target 'armv6-unknown-freebsd' is unavailable for download for channel 'nightly'
           # - armv7-unknown-freebsd  # fails to build
           # error: component 'rust-std' for target 'armv7-unknown-freebsd' is unavailable for download for channel 'nightly'
-          - armv5te-unknown-linux-gnueabi
-          - armv5te-unknown-linux-musleabi
-          - arm-linux-androideabi
-          - armv7-linux-androideabi
+          
           # - asmjs-unknown-emscripten
           # 199 |     compile_error!("unsupported target for `mio::unix::pipe`");
 
@@ -113,10 +125,6 @@ jobs:
           # # error: failed to run custom build command for `ring v0.16.20`
 
 
-          - aarch64-linux-android
-          - i686-linux-android
-          - x86_64-linux-android
-          
           # - wasm32-unknown-emscripten
           # 199 |     compile_error!("unsupported target for `mio::unix::pipe`");
 
@@ -128,10 +136,7 @@ jobs:
           # # error[E0425]: cannot find function `allocate` in module `sys`
           # #  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fs2-0.4.3/src/lib.rs:104:14
 
-
           # - x86_64-unknown-dragonfly
-
-
 
           # # error[E0463]: can't find crate for `std`
           # # |
@@ -144,13 +149,6 @@ jobs:
           # - thumbv7m-none-eabi
           # - thumbv8m.base-none-eabi
           # - thumbv8m.main-none-eabi
-
-
-
-
-          - thumbv7neon-linux-androideabi
-          - thumbv7neon-unknown-linux-gnueabihf
-
           
           # - x86_64-pc-windows-msvc
           # # --- stderr
@@ -260,7 +258,6 @@ jobs:
           file_glob: true
           tag: ${{ github.ref }}
 
-
   windows:
     runs-on: ${{ matrix.os }}
     defaults:
@@ -272,11 +269,11 @@ jobs:
         os: [windows-latest]
         crate: [pact_ffi]
         target:
-          - x86_64-pc-windows-msvc # ✅
-          - aarch64-pc-windows-msvc # ✅
-          - i686-pc-windows-msvc # ✅
-          - i686-pc-windows-gnu # ✅ with cross, native with cargo error: linker `i686-w64-mingw32-gcc` not found
-          - x86_64-pc-windows-gnu # ✅
+          # - x86_64-pc-windows-msvc # ✅
+          # - aarch64-pc-windows-msvc # ✅
+          # - i686-pc-windows-msvc # ✅
+          # - x86_64-pc-windows-gnu # ✅
+          - i686-pc-windows-gnu # native with cargo error: linker `i686-w64-mingw32-gcc` not found
           # - i586-pc-windows-msvc # Fails, could be possible. https://seri.tools/blog/compiling-rust-for-legacy-windows/
           # - aarch64-pc-windows-gnullvm
           # - aarch64-uwp-windows-msvc
@@ -320,92 +317,92 @@ jobs:
           file_glob: true
           tag: ${{ github.ref }}
 
-  macos:
-    runs-on: ${{ matrix.os }}
-    defaults:
-      run:
-        shell: bash
-    strategy:
-      fail-fast: false
-      matrix:
-        crate: [pact_ffi]
-        os: [macos-latest]
-        target:
-          - aarch64-apple-darwin # ✅
-          - x86_64-apple-darwin # ✅
-          - aarch64-apple-ios # ✅
-          - aarch64-apple-ios-sim # ✅
-          - x86_64-apple-ios # ✅
-          # - x86_64h-apple-darwin # https://doc.rust-lang.org/nightly/rustc/platform-support/x86_64h-apple-darwin.html
-          # - i686-apple-darwin
-          # - armv7k-apple-watchos
-          # - aarch64-apple-tvos
-          # - aarch64-apple-watchos-sim
-          # - arm64_32-apple-watchos
-          # - x86_64-apple-watchos-sim
-          # - x86_64-apple-tvos
-          # - armv7s-apple-ios
-          # - armv7-apple-ios
-          # - aarch64-apple-ios-macabi
-          # - x86_64-apple-ios-macabi
-          # - i386-apple-ios
-    steps:
-      - uses: actions/checkout@v3
-      - run: rustc --version || true
-        shell: bash
-      - uses: dtolnay/rust-toolchain@stable
-        continue-on-error: true
-        with:
-          toolchain: stable
-          target: ${{ matrix.target }}
-      - name: Build ${{ matrix.crate }} with cross for ${{ matrix.target }}
-        run: ./build-cross.sh
-        working-directory: rust/${{ matrix.crate }}
-        shell: bash
-        env:
-          target: ${{ matrix.target }}
-      - name: Show ${{ matrix.crate }} release
-        run: ls && ls ../../artifacts
-        working-directory: rust/target/${{ matrix.target }}/release
-        shell: bash
-      - name: Upload the artifacts
-        uses: actions/upload-artifact@v3.1.2
-        with:
-          name: release-artifacts
-          path: rust/target/artifacts
-      - name: Upload Release Assets
-        if: (startsWith(github.ref, 'refs/tags/libpact_ffi')  || startsWith(github.ref, 'refs/tags/pact_verifier_cli') || startsWith(github.ref, 'refs/tags/pact_mock_server_cli'))
-        uses: svenstaro/upload-release-action@2.5.0
-        with:
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          file: rust/target/artifacts/*
-          file_glob: true
-          tag: ${{ github.ref }}
+  # macos:
+  #   runs-on: ${{ matrix.os }}
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       crate: [pact_ffi]
+  #       os: [macos-latest]
+  #       target:
+  #         - aarch64-apple-darwin # ✅
+  #         - x86_64-apple-darwin # ✅
+  #         - aarch64-apple-ios # ✅
+  #         - aarch64-apple-ios-sim # ✅
+  #         - x86_64-apple-ios # ✅
+  #         # - x86_64h-apple-darwin # https://doc.rust-lang.org/nightly/rustc/platform-support/x86_64h-apple-darwin.html
+  #         # - i686-apple-darwin
+  #         # - armv7k-apple-watchos
+  #         # - aarch64-apple-tvos
+  #         # - aarch64-apple-watchos-sim
+  #         # - arm64_32-apple-watchos
+  #         # - x86_64-apple-watchos-sim
+  #         # - x86_64-apple-tvos
+  #         # - armv7s-apple-ios
+  #         # - armv7-apple-ios
+  #         # - aarch64-apple-ios-macabi
+  #         # - x86_64-apple-ios-macabi
+  #         # - i386-apple-ios
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - run: rustc --version || true
+  #       shell: bash
+  #     - uses: dtolnay/rust-toolchain@stable
+  #       continue-on-error: true
+  #       with:
+  #         toolchain: stable
+  #         target: ${{ matrix.target }}
+  #     - name: Build ${{ matrix.crate }} with cross for ${{ matrix.target }}
+  #       run: ./build-cross.sh
+  #       working-directory: rust/${{ matrix.crate }}
+  #       shell: bash
+  #       env:
+  #         target: ${{ matrix.target }}
+  #     - name: Show ${{ matrix.crate }} release
+  #       run: ls && ls ../../artifacts
+  #       working-directory: rust/target/${{ matrix.target }}/release
+  #       shell: bash
+  #     - name: Upload the artifacts
+  #       uses: actions/upload-artifact@v3.1.2
+  #       with:
+  #         name: release-artifacts
+  #         path: rust/target/artifacts
+  #     - name: Upload Release Assets
+  #       if: (startsWith(github.ref, 'refs/tags/libpact_ffi')  || startsWith(github.ref, 'refs/tags/pact_verifier_cli') || startsWith(github.ref, 'refs/tags/pact_mock_server_cli'))
+  #       uses: svenstaro/upload-release-action@2.5.0
+  #       with:
+  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
+  #         file: rust/target/artifacts/*
+  #         file_glob: true
+  #         tag: ${{ github.ref }}
 
 
-  build_headers:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - run: rustc --version || true
-        shell: bash
-      - uses: dtolnay/rust-toolchain@stable
-        with:
-          toolchain: stable
-      - name: Build headers with cargo pact_ffi
-        run: ./build-headers.sh
-        working-directory: rust/pact_ffi
-        shell: bash
-      - name: Upload the artifacts
-        uses: actions/upload-artifact@v3.1.2
-        with:
-          name: release-artifacts
-          path: rust/target/artifacts
-      - name: Upload Release Assets
-        if: startsWith(github.ref, 'refs/tags/libpact_ffi')
-        uses: svenstaro/upload-release-action@2.5.0
-        with:
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          file: rust/target/artifacts/*
-          file_glob: true
-          tag: ${{ github.ref }}
+  # build_headers:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - run: rustc --version || true
+  #       shell: bash
+  #     - uses: dtolnay/rust-toolchain@stable
+  #       with:
+  #         toolchain: stable
+  #     - name: Build headers with cargo pact_ffi
+  #       run: ./build-headers.sh
+  #       working-directory: rust/pact_ffi
+  #       shell: bash
+  #     - name: Upload the artifacts
+  #       uses: actions/upload-artifact@v3.1.2
+  #       with:
+  #         name: release-artifacts
+  #         path: rust/target/artifacts
+  #     - name: Upload Release Assets
+  #       if: startsWith(github.ref, 'refs/tags/libpact_ffi')
+  #       uses: svenstaro/upload-release-action@2.5.0
+  #       with:
+  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
+  #         file: rust/target/artifacts/*
+  #         file_glob: true
+  #         tag: ${{ github.ref }}
